config/routes.rb
Aplikacja1::Application.routes.draw do

  devise_for :admins
  devise_for :users

  resources :programs do
    resources :episodes
  end

  resources :episodes do
    resources :comments
  end

  resources :topics
  resources :articles
  resources :comments
  resources :home

  get "/admin/" => "admin#index", as: "admin_dashboard"

  root :to => "home#index"
  get "/kontakt/" => "home#contact"
  get "/o-nas/" => "home#about_us"
  get "/reklama/" => "home#advertise"

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_many :programs
  has_many :topics


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :topic
  has_many :comments, :as => :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :user_id, presence: true


  def self.can_edit?(user)
    self.user ==user
  end



end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :program
  has_many :comments,  :as => :commentable

  def self.find_episodes(program_id)
    if program_id
      Episode.where(:program_id => program_id)
    else
      Episode.all
    end
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :admin
  has_many :episodes
  has_attached_file :image, :styles => { :medium => "100x100>", :thumb => "100x100>" }

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :admin
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :admin_signed_in?      # autoryzację admina

  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end

  def about_us
  end

  def advertise
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def create
    @user = User.new(user_params)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/index.html.erb
<head>
  <title>Admin panel</title>
  <link rel="stylesheet" type="text/css" href="all.css">
</head>

<body class="body">

    <div class="admin-panel">

        <h1 class="admin-header">Admin panel</h1>

        <div class="admin-dashboard-block">
          <%= link_to "Programs", programs_path, class: "btn btn-primary btn-lg btn-block" %>
          <%= link_to "Episodes", episodes_path, class: "btn btn-primary btn-lg btn-block" %>
          <%= link_to "Topics", topics_path, class: "btn btn-primary btn-lg btn-block" %>
          <%= link_to "Articles", articles_path, class: "btn btn-primary btn-lg btn-block" %>
        </div>

      <div class="admin-dashboard-block">
        <%= link_to "Add programs", new_program_path, class: "btn btn-success btn-lg btn-block" %>
        <%= link_to "Add episode", new_episode_path, class: "btn btn-success btn-lg btn-block" %>
        <%= link_to "Add topic", new_topic_path, class: "btn btn-success btn-lg btn-block" %>
        <%= link_to "Add article", new_article_path, class: "btn btn-success btn-lg btn-block" %>
      </div>



        <div class="admin-dashboard-block-comments" >
          <%= link_to "Comments", comments_path, class: "btn btn-primary btn-lg btn-block" %>
          <table class="table table-striped" >
            <tr>
              <th>Comment</th>
              <th>User</th>
            </tr>
            <tr>
              <td>Comment1</td>
              <td>User1</td>
            </tr>
            <tr>
              <td>Comment1</td>
              <td>User1</td>
            </tr>
          </table>

        </div>
    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DlaNiejTv" %></title>


    <link rel="stylesheet" type="text/css" href="nav.css">


    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>


<% programs = Program.all %>
<% episodes = Episode.all %>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <a class="brand"  href="http://www.dlaniej.tv"><%= image_tag 'dlaniejlogo.jpg' %></a>




          <ul id="nav">
            <li><%= link_to "Strona główna",home_index_path %></li>
            <li>
              <%= link_to "Programy",programs_path %>
              <ul>
                <% programs.each do |p|  %>
                   <li><%= link_to p.name,program_episodes_path(p) %>
                      <ul>
                        <% p.episodes.find_each do |e|  %>
                        <li><%= link_to e.title,episode_path(e)%></li>
                        <% end %>
                      </ul>
                    </li>
                <% end %>
              </ul>
            </li>
            <li>
              <%= link_to "Wszystkie odcinki",episodes_path %>
              <ul>
                <% episodes.each do |i|  %>
                    <li><%= link_to i.title,episode_path(i)%></li>
                <% end %>
              </ul>
            </li>

            <li><%= link_to "O nas","./o-nas" %></li>
            <li><%= link_to "Reklama","./reklama" %></a></li>
            <li><%= link_to "Kontakt","./kontakt" %></li>
          </ul>


          <div id="login_panel">
            <%= link_to "User sign in", "../users/sign_in", class: "btn btn-success btn-xs "%>
            <% if current_admin %>
                <%= link_to "Admin panel", "./admin", class: "btn btn-primary btn-xs " %>
            <% end %>
            <ul id="login_panel_list">


              <li><%= link_to "User sign up","../users/sign_up" %></li>
              <li><%= link_to "Admin sign in","../admins/sign_in" %></li>

              <% if current_admin %>
                  <li><%= link_to "Admin log out",  destroy_admin_session_path, :method => :delete %></li>
              <% end %>

              <% if current_user %>
                  <li><%= link_to "User log out",  destroy_user_session_path, :method => :delete %></li>
              <% end %>

            </ul>
          </div>



          <div class="container-fluid nav-collapse">
            <ul class="nav">

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <%= bootstrap_flash %>
    <%= yield %>

    <script src="./nav.js"></script>

  </body>
</html>